apiVersion: v1
kind: Pod
metadata:
  name: hashicorp-vault
  labels:
    app: hashicorp-vault
spec:
  containers:
  - name: hashicorp-vault
    image: hashicorp/vault:1.18.2
    ports:
    - containerPort: 8200

